### ISSUE TITLE
[Question] Could the base code be used to create a viewbot?

### ISSUE THREAD

**Issue by pythonnoob2** [MagicaFreak/Python-TwitchAPI#1]
Sorry if this is not the right place to ask, I am still new to Github.  Since this connects directly to Twitch Api, could this code be "upgraded" to create a view bot with proxies? 

No offense to the project creator is intended.  Just looking to create something small for myself and have been having trouble with the old codes i've been finding.

**Comment by MagicaFreak** [comment]
That would be someday the goal but at the moment it only uses the Twitch App token so it can gets active streams and users and their information but not at the moment to talk with the chat or can do anything on your account. So im sorry to say you cant do a viewbot with this at the moment

**Comment by pythonnoob2** [comment]
Thanks for responding and explaining.  Cheers!
